aioforum/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # maps everything that starts with questions to that app's urls
    path('questions/', include('questions.urls')),
    path('', RedirectView.as_view(url = 'questions/', permanent = True)),
    # Maps everything that requires peer access to that application.
] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

questions/urls.py
from django.urls import path
from . import views

urlpatterns = [
   # path('', views.PublicQuestionListView.as_view(), name='index'),

    path('ask', views.submit_question, name='submit-question'),
    path('success', views.submit_question_success, name='submit-success'),

    # Public access.
    path('ajax/categories', views.getCategories, name='get_categories'),

    path('', views.public_question_list, name='index'),
    path('all/', views.PublicQuestionList.as_view(), name='public-all'),
    path('<slug:slug>', views.QuestionDetailView.as_view(),
        name='question-detail'),

    # Peer access only.
    # Question list.
    path('peaccess/all', views.all_question_list, name='peaccess'),
    path('peaccess/all/get', views.AllQuestionList.as_view(), name='pe-all'),
    # Edit questions.
    path('peaccess/<slug:slug>/edit',
        views.QuestionEditView.as_view(), name='edit-question'),
    # Edit categories.
    path('categories/', views.CategoryListAddView.as_view(),
        name='add-view-category'),
]

questions/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from django.conf import settings

import uuid
import itertools

# Create your models here.

# Abstract parent model for questions. Contains information that all private
# and public questions should have
# Does not actually function as a model that holds information
class Question(models.Model):
    """ Some constants. """
    # Choices for status of the question.
    PUBLIC = 'p'
    ANSWERED = 'a'
    NEW = 'n'

    # Question status
    STATUS = (
        (NEW, 'New'),
        (ANSWERED, 'Answered'),
        (PUBLIC, 'Public'),
    )

    # A unique slug for each question: as URL identifier
    slug = models.SlugField(unique = True,
        default='',
        max_length=settings.QUESTION_SLUG_MAX_LEN)

    # Subject of the question
    subject = models.CharField(max_length=settings.QUESTION_SUBJECT_MAX_LEN,
        help_text='Summarize your question.')

    # Content of the question
    content = models.TextField(max_length=settings.LONG_TEXT_MAX_LEN,
        help_text='State your question here')

    # The date and time of the post. Edited automatically
    post_date = models.DateTimeField(auto_now_add = True)

    # Reply edited later by peer.
    reply =  models.TextField(max_length=settings.LONG_TEXT_MAX_LEN,
        help_text='State your reply here',
        null=True, blank=True,)

    # categories of the question. Only editable by the admin
    category = models.ManyToManyField('Category',
        help_text='Select categories applicable for this question',
        blank=True)

    # If the op wants to get an email notification, optional
    # Will be removed once the reply has been sent
    op_email = models.EmailField(blank = True)

    status = models.CharField(
        max_length =1, # Can only have 1 status at a time.
        choices = STATUS,
        blank = True,
        default = 'n',
        help_text = 'Question status.'
    )

    class Meta:
        # Set to display the newest first
        ordering = ['-post_date']

    # Generate a unique slug by adding a unique number after the title.
    # Reference:
    """
    https://djangosnippets.org/snippets/10643/
    """
    def _generate_slug(self):
        # First get the original slugified result.
        origin_slug = slugify(self.subject)
        unique_slug = origin_slug
        # Loop through all slugs to check uniqueness.
        numb = 1
        while Question.objects.filter(slug=unique_slug).exists():
            unique_slug = '%s-%d' % (origin_slug, numb)
            numb += 1

        self.slug = unique_slug

    def save(self, *args, **kwargs):
        # If new record is being created, generate the slug.
        if self._state.adding:
            self._generate_slug()
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        kwargs = {'slug': self.slug, 'pk': self.pk}
        return reverse('question-detail', kwargs=kwargs)

    # Set this instance's status to answered.
    def set_to_answered(self):
        self.status = 'a'

    # Set this instance's status to public.
    def set_to_public(self):
        self.status = 'p'

# Category model to hold information about a category
class Category(models.Model):
    """Model representing the category of a question"""
    name = models.CharField(max_length = settings.CATEGORY_NAME_MAX_LEN,
        help_text = 'Enter the name of the category')

    def __str__(self):
        """String for representing this category object"""
        return self.name

# Reply model to hold information about a reply
class Reply(models.Model):
    """Model representing a reply to a question"""

    # Content of the reply
    content = models.TextField(max_length = settings.LONG_TEXT_MAX_LEN,
        help_text = 'State your reply here')

    # The date and time of the reply. Edited automatically
    post_date = models.DateTimeField(auto_now = True)

questions/forms.py
from django import forms
from django.forms.models import modelformset_factory

from questions.models import Category, Question, Reply

# For students to submit a question.
class SubmitQuestionForm(forms.Form):
    subject = forms.CharField(
        help_text='Summarize your question under 100 words.',
        max_length=100)

    content = forms.CharField(
        help_text='Explain it further there',
        widget=forms.Textarea,
        max_length=1000)

    email = forms.EmailField(
        help_text='Optional. Receive notification.',
        required=False)

class BaseCategoryFormSet(forms.BaseModelFormSet):
    """ Validate formset: make sure there is no duplicate names
        for categories."""

    def clean(self):
        """Check if the category has already existed."""
        if any(self.errors): # If any individual data has error, it's error.
            return

        # Get an array of category names already existed.
        existed_categories = Category.objects.all();
        existed_names = []
        for category in existed_categories:
            existed_names.append(category.name)

        # Array to store duplicated category names.
        duplicate_names = []
        # Check if there are repeating category names.
        for form in self.forms:
            # Get each category name from form.
            name = form.cleaned_data.get('name')
            # If name already existed, raise error to let user know.
            if name in existed_names and not name in duplicate_names:
                duplicate_names.append(name)
            else:
                existed_names.append(name)

        # If the duplicated list is not empty, raise an error.
        if duplicate_names:
            raise forms.ValidationError(
                ('Duplicated category: %(name)s'),
               code='duplicate',
               params={'name': ' '.join(duplicate_names)},
            )

# Allow user to add as many categories as they want, one at a time.
CategoryFormSet = modelformset_factory(Category, formset=BaseCategoryFormSet,
    fields=('name',), extra=0, can_delete=True)

questions/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic.edit import UpdateView, DeletionMixin, CreateView
from django.views.generic.edit import FormView

from django.conf import settings

from questions.models import Category, Question
from questions.forms import SubmitQuestionForm, CategoryFormSet

import datetime

# Create your views here.

class PublicQuestionListView(generic.ListView):
    paginate_by = settings.PAGINATE_BY
    model = Question
    # Only show questions that has been published.
    queryset = Question.objects.filter(status__iexact=Question.PUBLIC)

class QuestionDetailView(generic.DetailView):
    model = Question

# Show all the questions. Only Peers should have access to this.
class AllQuestionListView(generic.ListView):
    # Get all the questions from the database.
    paginate_by = settings.PAGINATE_BY
    model = Question

    # Use a different template since we want a different filter option on top.
    template_name = 'questions/peeraccess_question_list.html'

# Show the questions based on filtered results.
class QuestionByStatusListView(generic.ListView):
    paginate_by = settings.PAGINATE_BY

    # Use a different template since we want a different filter option on top.
    template_name = 'questions/peeraccess_question_list.html'

    # Filter the questions by their status.
    def get_queryset(self):
        status = self.kwargs['status']
        return Question.objects.filter(status__iexact=status)

# Peer access to update a question.
# Reference: https://stackoverflow.com/questions/51772361/
# how-to-include-delete-function-in-updateview-instead-a-deleteview
class QuestionEditView(DeletionMixin, UpdateView):
    model = Question
    fields = ['category', 'reply', 'status']
    template_name = 'questions/edit_question.html'
    success_url = reverse_lazy('peaccess')

    def post(self, request, *args, **kwargs):
        """ Handling update and delete quests in the form differently. """
        # When updating, manually update the quesiton object.
        if 'update_question' in self.request.POST:
            # Get the reference to the form and the question being edited.
            form = self.get_form()
            question = self.get_object()

            if form.is_valid():
                # Udpate the question with form data.
                question.reply = form.cleaned_data['reply']
                question.status = form.cleaned_data['status']
                # Clean the many-to-many field of category.
                question.category.clear()
                # Iterate through all the categories and add each one.
                for category in form.cleaned_data['category']:
                    question.category.add(category)
                question.save()

            return HttpResponseRedirect(reverse('submit-success'))

        else: # if 'delete_question' in self.request.POST, use deletionmixin.
            return self.delete(request, *args, **kwargs)


class CategoryListAddView(FormView):
    """ Display formset of categories for editing existed categories and adding
        new ones."""

    form_class = CategoryFormSet
    success_url = reverse_lazy('peaccess')
    template_name = 'questions/view_add_category.html'

    def form_valid(self, form):
        """ Save all the new names as new categories in the database. """
        form.save()

        # Return to success_url
        return HttpResponseRedirect(self.get_success_url())

def submit_question(request):
    # If this is a POST request then process form data
    if request.method == 'POST':
        # Grab the question from the request
        form = SubmitQuestionForm(request.POST)

        # Check if the question is actually valid
        if form.is_valid():
            # If it is, then create a new PrivateQuestion data
            new_question = Question(
                subject = form.cleaned_data['subject'],
                content = form.cleaned_data['content'],
                post_date = datetime.date.today())

            # If op choses to give us his email, record it
            if form.data['email']:
                new_question.op_email = form.cleaned_data['email']

            # Query the new question to the database
            new_question.save()

            return HttpResponseRedirect(reverse('submit-success'))

    # If this is a GET request then give out the new form
    else:
        form = SubmitQuestionForm()

    context = {'form': form, }

    return render(request, 'questions/submit_question.html', context)

def submit_question_success(request):
    # Render the success page.
    return render(request, 'questions/submit_question_success.html')


def all_question_list(request):
    return render(request, 'questions/peaccess_questions.html')

"""Testing using rest and ajax to dynamically filter."""

from django.http import JsonResponse
from django.shortcuts import render
from rest_framework.generics import ListAPIView
from .serializers import QuestionSerializers
from .models import Question, Category
from .pagination import StandardResultsSetPagination


class AllQuestionList(ListAPIView):
    serializer_class = QuestionSerializers
    pagination_class = StandardResultsSetPagination

    def get_queryset(self):

        # For filtering by which time frame the qusetoin is posted in.
        DAY = 'Past Day'
        WEEK = 'Pask Week'
        MONTH = 'Past Month'
        YEAR = 'Past Year'
        DAYS_A_WEEK = 7
        DAYS_A_MONTH = 30
        DAYS_A_YEAR = 365

        POST_DATE_CHOICES = {
            DAY: 1,
            WEEK: DAYS_A_WEEK,
            MONTH: DAYS_A_MONTH,
            YEAR: DAYS_A_YEAR,
        }

        # Query based on filters applied.
        query_list = Question.objects.all()
        category = self.request.query_params.get('categories', None)
        post_date = self.request.query_params.get('post_in', None)
        status = self.request.query_params.get('status', None)
        sort_by = self.request.query_params.get('sort_by', None)

        # If category filters applied:
        if category:
            # Get all the questions whose category matches at least one of the
            # applied categories.
            query_list = query_list.filter(category__id=category).distinct()

        # If post_date filter applied:
        if post_date:
            query_list = query_list.filter(
                post_date__gt=datetime.datetime.today() -
                    datetime.timedelta(days=(POST_DATE_CHOICES.get(
                    post_date, DAYS_A_YEAR)))
            )

        # If status filter applied:
        if status:
            query_list = query_list.filter(status__iexact=status)

        # After query, if sort_by filter applied:
        if sort_by:
            if sort_by == 'Oldest First':
                # Order by date, ascending as dates get newer/bigger.
                query_list = query_list.order_by('post_date')
            else:
                query_list = query_list.order_by('-post_date')

        return query_list


def getCategories(request):
    # Return all the categories.
    if request.method == 'GET' and request.is_ajax():
        # Get all the question objects.
        category_objs = Category.objects.all()
        # List the name out to be a string array.
        category_names = []
        for cat in category_objs:
            category_names.append(cat.id)

        data = {
            'categories': category_names,
        }
        return JsonResponse(data, status=200)

questions/templates/questions/edit_question.html
{% extends "base_generic.html" %}

{% block content %}
  {{ question.subject }}
  <hr>
  {{ question.content }}
  <hr>
  {{ question.post_date }}
  <hr>
  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div>
      <input type="submit" name="update_question" value="Update"
        onclick="return confirm('Sure to save?');"/>
      <input type="submit" name="delete_question" value="Delete"
        onclick="return confirm('Sure to Delete?');"/>
    </div>
  </form>

{% endblock %}

questions/templates/questions/peaccess_questions.html
{% extends "base_generic.html" %}
{% load static %}
{% block style %}
    <style type="text/css">
    .properties_table{
       min-height: 540px;
       font-size: 14px;
    }
    </style>
{% endblock %}


{% block script %}
  <script src="{% static 'js/filters.js' %}" type="text/javascript">
  </script>
{% endblock %}

{% block content %}
  <section class="site_filter">
    <div class="container-fluid">
      <div class="row">

        <!-- Category options. -->
        <div class="col-sm-2 col-2">
          <div class="form-group">
            <label for="category">Category</label>
            <select class="form-control" id="categories"
                    url = "{%url 'get_categories' %}">
            </select>
          </div>
        </div>

        <!-- Sorting options. -->
        <div class="col-sm-2 col-2">
          <div class="form-group">
            <label for="sort">Sort By</label>
            <select class="form-control" id="sort_by">
              <option selected="true"
                      disabled="disabled" value = "none">Choose option</option>
              <option value='Oldest First'>Oldest First</option>
              <option value='Newest First'>Newest First</option>
            </select>
          </div>
        </div>

        <!-- Post date options. -->
        <div class="col-sm-2 col-2">
          <div class="form-group">
            <label for="post-date">Post In</label>
            <select class="form-control" id="post_in">
              <option selected="true"
                      value = "none">All</option>
              <option value='Past Day'>Past Day</option>
              <option value='Past Week'>Past Week</option>
              <option value='Past Month'>Past Month</option>
              <option value='Past Year'>Past Year</option>
            </select>
          </div>
        </div>

        <!-- Status options. -->
        <div class="col-sm-2 col-2">
          <div class="form-group">
            <label for="post-date">Status</label>
            <select class="form-control" id="status">
              <option selected="true"
                      value = "none">All</option>
              <option value='a'>Answered</option>
              <option value='p'>Public</option>
              <option value='n'>New</option>
            </select>
          </div>
        </div>

        <div class="col-sm-2 col-2">
          <div class="row justify-content-center align-self-center"
               style="color:white; margin-top:30px;">
            <a class="btn btn-secondary" id="display_all">Display all</a>
          </div>
        </div>
      </div>
    </div>
  </section>

  <br />

  <section>
    <div class="container-fluid">
      <div id = "result-count" class="text-right">
        <span class='font-weight-bold'></span> results found.
      </div>
      <div class="row properties_table justify-content-center">
        <div id = "no_results">
          <h5>No results found</h5>
        </div>
        <table class="table table-bordered table-responsive table-hover table-striped"
               id="list_data" data-toggle="table" url = "{% url 'pe-all' %}">
          <thead>
            <tr>
              <th data-field="subject">subject</th>
              <th data-field="content">content</th>
              <th data-field="category">category</th>
            </tr>
          </thead>
          <tbody id="listing">
          </tbody>
        </table>
      </div>

      <div class="row justify-content-center">
        <nav aria-label="navigation">
          <ul class="pagination">
            <li class="page-item">
              <button class="btn btn-primary page-link" id="previous">Previous</button>
            </li>
            <li class="page-item pull-right">
              <button class="btn btn-primary page-link" id="next">Next</button>
            </li>
          </ul>
        </nav>
      </div>

    </div>
  </section>

{% endblock %}

questions/templates/questions/peeraccess_question_list.html
{% extends "base_generic.html" %}

{% load static %}

{% block style %}
  <link rel="stylesheet" type="text/css"
        href="{% static 'questions/search.css' %}">
  <link rel="stylesheet" type="text/css"
        href="{% static 'questions/index.css' %}">
{% endblock %}

{% block script %}
  <script src="{% static 'js/filter.js' %}"></script>
{% endblock %}

{% block content %}
  <input type="text" class="search-bar" placeholder="...">

  {% if question_list %}
    <ul class="question-list">
      {% for question in question_list %}
        <li class="question-list-item">
          <details>
            <summary>{{ question.subject }}</summary>
            {{ question.content }}
            <hr>
            {{ question.post_date }}
            <hr>
            {% if question.category.all %}
              Categories:
              {% for category in question.category.all %}
                {{ category.name }}
              {% endfor %}
            {% endif %}

            {% if question.reply %}
              <hr>
              {{ question.reply }}
            {% endif %}
            <hr>
            <a href="{% url 'edit-question' question.slug %}">Edit</a>
          </details>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    There is no question in the database.
  {% endif %}
{% endblock %}

questions/templates/questions/public_question.html
{% extends "base_generic.html" %}
{% load static %}
{% block style %}
    <style type="text/css">
    .properties_table{
       min-height: 540px;
       font-size: 14px;
    }
    </style>
{% endblock %}


{% block script %}
  <script src="{% static 'js/filters.js' %}" type="text/javascript">
  </script>
{% endblock %}

{% block content %}
  <section class="site_filter">
    <div class="container-fluid">
      <div class="row">

        <!-- Category options. -->
        <div class="col-sm-2 col-2">
          <div class="form-group">
            <label for="category">Category</label>
            <select class="form-control" id="categories"
                    url = "{%url 'get_categories' %}">
            </select>
          </div>
        </div>

        <!-- Sorting options. -->
        <div class="col-sm-2 col-2">
          <div class="form-group">
            <label for="sort">Sort By</label>
            <select class="form-control" id="sort_by">
              <option selected="true"
                      disabled="disabled" value = "none">Choose option</option>
              <option value='Oldest First'>Oldest First</option>
              <option value='Newest First'>Newest First</option>
            </select>
          </div>
        </div>

        <!-- Post date options. -->
        <div class="col-sm-2 col-2">
          <div class="form-group">
            <label for="post-date">Post In</label>
            <select class="form-control" id="post_in">
              <option selected="true"
                      value = "none">All</option>
              <option value='Past Day'>Past Day</option>
              <option value='Past Week'>Past Week</option>
              <option value='Past Month'>Past Month</option>
              <option value='Past Year'>Past Year</option>
            </select>
          </div>
        </div>

        <div class="col-sm-2 col-2">
          <div class="row justify-content-center align-self-center"
               style="color:white; margin-top:30px;">
            <a class="btn btn-secondary" id="display_all">Display all</a>
          </div>
        </div>
      </div>
    </div>
  </section>

  <br />

  <section>
    <div class="container-fluid">
      <div id = "result-count" class="text-right">
        <span class='font-weight-bold'></span> results found.
      </div>
      <div class="row properties_table justify-content-center">
        <div id = "no_results">
          <h5>No results found</h5>
        </div>
        <table class="table table-bordered table-responsive table-hover table-striped"
               id="list_data" data-toggle="table" url = "{% url 'public-all' %}">
          <thead>
            <tr>
              <th data-field="subject">subject</th>
              <th data-field="content">content</th>
              <th data-field="category">category</th>
            </tr>
          </thead>
          <tbody id="listing">
          </tbody>
        </table>
      </div>

      <div class="row justify-content-center">
        <nav aria-label="navigation">
          <ul class="pagination">
            <li class="page-item">
              <button class="btn btn-primary page-link" id="previous">Previous</button>
            </li>
            <li class="page-item pull-right">
              <button class="btn btn-primary page-link" id="next">Next</button>
            </li>
          </ul>
        </nav>
      </div>

    </div>
  </section>

{% endblock %}

questions/templates/questions/question_detail.html
{% extends "base_generic.html" %}

{% block content %}

  {{ question.subject }}
  <hr>
  {{ question.content }}
  <hr>
  {{ question.post_date }}

  {% if question.reply %}
    <hr>
    {{ question.reply.content }}
  {% endif %}

{% endblock %}

questions/templates/questions/question_list.html
{% extends "base_generic.html" %}

{% load static %}

{% block style %}
  <link rel="stylesheet" type="text/css"
        href="{% static 'questions/search.css' %}">
  <link rel="stylesheet" type="text/css"
        href="{% static 'questions/index.css' %}">
{% endblock %}

{% block script %}
  <script src="{% static 'js/filter.js' %}"></script>
{% endblock %}

{% block content %}
  <input type="text" class="search-bar" placeholder="...">

  {% if question_list %}
    <ul class="question-list">
      {% for question in question_list %}
        <li class="question-list-item">
          <details>
            <summary>{{ question.subject }}</summary>
            {{ question.content }}
            <hr>
            {{ question.post_date }}
            <hr>
            {% if question.category.all %}
              Categories:
              {% for category in question.category.all %}
                {{ category.name }}
              {% endfor %}
            {% endif %}

            {% if question.reply %}
              <hr>
              {{ question.reply }}
            {% endif %}
            <hr>
            <a href="{{ question.get_absolute_url }}">Read More</a>
          </details>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    There is no question in the database.
  {% endif %}
{% endblock %}

questions/templates/questions/submit_question.html
{% extends "base_generic.html" %}

{% block content %}

  <form action="" method="post">
    {% csrf_token %}
    <div>
      {{ form.subject }}
    </div>
    <div>
    {{ form.content }}
    </div>
    <div>
    {{ form.email }}
    </div>
    <input type="submit" value="Submit">
  </form>

{% endblock %}

questions/templates/questions/submit_question_success.html
{% extends "base_generic.html" %}

{% block content %}
  <p>You have successfully submitted a question!</p>
{% endblock %}

questions/templates/questions/test2.html
{% extends "base_test.html" %}
{% load static %}
{% block style %}
    <style type="text/css">
    .properties_table{
       min-height: 540px;
       font-size: 14px;
    }
    </style>
{% endblock %}

{% block content %}
  <section class="site_filter">
    <div class="container-fluid">
      <div class="row">

        <!-- Category options. -->
        <div class="col-sm-2 col-2">
          <div class="form-group">
            <label for="category">Category</label>
            <select class="form-control" id="categories"
                    url = "{%url 'get_categories' %}">
            </select>
          </div>
        </div>

        <!-- Sorting options. -->
        <div class="col-sm-2 col-2">
          <div class="form-group">
            <label for="sort">Sort By</label>
            <select class="form-control" id="sort_by">
              <option selected="true"
                      disabled="disabled" value = "none">Choose option</option>
              <option value='Oldest First'>Oldest First</option>
              <option value='Newest First'>Newest First</option>
            </select>
          </div>
        </div>

        <!-- Post date options. -->
        <div class="col-sm-2 col-2">
          <div class="form-group">
            <label for="post-date">Post In</label>
            <select class="form-control" id="post_in">
              <option selected="true"
                      value = "none">All</option>
              <option value='Past Day'>Past Day</option>
              <option value='Past Week'>Past Week</option>
              <option value='Past Month'>Past Month</option>
              <option value='Past Year'>Past Year</option>
            </select>
          </div>
        </div>

        <!-- Status options. -->
        <div class="col-sm-2 col-2">
          <div class="form-group">
            <label for="post-date">Status</label>
            <select class="form-control" id="status">
              <option selected="true"
                      value = "none">All</option>
              <option value='a'>Answered</option>
              <option value='p'>Public</option>
              <option value='n'>New</option>
            </select>
          </div>
        </div>

        <div class="col-sm-2 col-2">
          <div class="row justify-content-center align-self-center"
               style="color:white; margin-top:30px;">
            <a class="btn btn-secondary" id="display_all">Display all</a>
          </div>
        </div>
      </div>
    </div>
  </section>
  <br />
  <section>
    <div class="container-fluid">
      <div id = "result-count" class="text-right">
        <span class='font-weight-bold'></span> results found.
      </div>
      <div class="row properties_table justify-content-center">
        <div id = "no_results">
          <h5>No results found</h5>
        </div>
        <table class="table table-bordered table-responsive table-hover table-striped"
               id="list_data" data-toggle="table" url = "{% url 'test' %}">
          <thead>
            <tr>
              <th data-field="subject">subject</th>
              <th data-field="content">content</th>
              <th data-field="category">category</th>
            </tr>
          </thead>
          <tbody id="listing">
          </tbody>
        </table>
      </div>
      <div class="row justify-content-center">
        <nav aria-label="navigation">
          <ul class="pagination">
            <li class="page-item">
              <button class="btn btn-primary page-link" id="previous">Previous</button>
            </li>
            <li class="page-item pull-right">
              <button class="btn btn-primary page-link" id="next">Next</button>
            </li>
          </ul>
        </nav>
      </div>
    </div>
  </section>
{% endblock %}

{% block script %}
  <script src="{% static 'js/filters.js' %}" type="text/javascript">
  </script>
{% endblock %}